# Generated by Django 3.2.18 on 2023-02-19 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', null=True)),
                ('deleted_flag', models.IntegerField(blank=True, db_column='deleted_flag', default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('color', models.CharField(blank=True, db_column='color', max_length=255)),
                ('logo', models.CharField(blank=True, db_column='logo', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', null=True)),
                ('deleted_flag', models.IntegerField(blank=True, db_column='deleted_flag', default=0, null=True)),
                ('brand', models.ForeignKey(blank=True, db_column='brand_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brand_name', to='models.brand')),
            ],
        ),
    ]
